blank_issues_enabled: true
contact_links:
  - name: Join our GitHub Discussions community
    url: https://github.com/kukhariev/ngx-uploadx/discussions
    about: Ask questions and discuss with other community members
