name: playwright
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened]
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: './.github/actions/cached-npm-install'
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test -c e2e/playwright.config.ts
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
